name: spark
author: Chrome Team <apps-dev@chromium.org>
version: 0.1.4-dev
homepage: https://github.com/GoogleChrome/spark
description: A Chrome app based development environment.
dependencies:
  ace: '>=0.1.3'
  analyzer: any
  bootjack: any
  browser: any
  chrome_gen: '>=0.3.0'
  crc32: 0.1.3
  crypto: any
  intl: any
  logging: any
  mime: any
  spark_widgets:
    path: ../widgets
  unittest: any
dev_dependencies:
  args: any
  grinder: '>=0.4.2'
